title:             Webz Website
email:             all@webz.website
description:       Get your Daily digest of important products
author:            Adam Leal
baseurl:           ""
url:               "http://read.webz.website"

# Social Profiles
twitter_username:
github_username:
facebook_username: seoleal

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-target-blank

include: ['_categories', '_spanish', '_pages']
permalink: /:year/:month/:day/:title.html
